name: Java CI with Gradle (Regular)

on: [push, workflow_dispatch]

jobs:
  build:
    strategy: 
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          java: [ 11, 17, 21 ]
        fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    steps:
    - name: Set Git Property and output path
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          git config --system core.longpaths true
        fi
      shell: bash
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Run Unit Tests
      run: ./gradlew test
    - name: Publish Test Report ${{ matrix.java }} OS ${{ matrix.os }}
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         report_paths: '**/build/test-results/test/TEST-*.xml'
         check_name: Test Report ${{ matrix.java }} OS ${{ matrix.os }}
    - name: Upload Unit Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results (Java ${{ matrix.java }} OS ${{ matrix.os }})
        path: '**/build/test-results/test/TEST-*.xml'
