name: Java CI with Gradle (PR)

on: pull_request

jobs:
  build:
    strategy: 
        matrix:
          os: [ubuntu-latest, windows-latest]
          java: [ 1.8, 11, 15 ]
        fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    steps:
    - name: Set Git Property and output path
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          git config --system core.longpaths true
        fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Run Unit Tests
      run: ./gradlew test
    - name: Upload Unit Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results (Java ${{ matrix.java }} OS ${{ matrix.os }})
        path: '**/build/test-results/test/TEST-*.xml'
